version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: orders_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=orders_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - orders-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  orders-data:
