version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: generated_numbers_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: